# Linear Algebra Review

## Scaler 标量, Vector 向量，Matrix 矩阵，Tensor 张量

### Scaler 标量

In [1]:
import torch

# Scaler
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x - y, x * y, x / y, x ** y

(tensor(5.), tensor(1.), tensor(6.), tensor(1.5000), tensor(9.))

### Vector 向量

In [3]:
# Vector
x = torch.arange(4)
x, x[3]

(tensor([0, 1, 2, 3]), tensor(3))

大量文献认为列向量是向量的默认方向，所以 `x` 是
```
0
1
2
3
```

#### 向量的长度、维度和形状

向量的长度跟维度一样，表示包含了几个元素。

In [4]:
# 用 array 的 len() 函数访问
len(x)

4

In [5]:
# 用 PyTorch tensor 的 shape attribute 访问
x.shape

torch.Size([4])

### Matrix 矩阵

矩阵将向量从一维推广到二维。

In [7]:
# 创建一个5行4列的矩阵
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

转置 (transpose) 一个矩阵
```
A[i][j] = A.T[j][i]
```

In [9]:
# 转置它为4行5列的矩阵
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

特殊矩阵：symmetric matrix
A = A.T

In [10]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B, B == B.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

### Tensor 张量

矩阵的推广， n维。

In [12]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 运算