## Run and connect to a local Jupyter server
1. Install Jupyter
```bash
$ pip3 install jupyter
```
2. Start the server
```bash
$ jupyter notebook
```
The server connection URI will be shown in the terminal in the format like the following
```
http://localhost:8889/?token=3537328d33241057ed984417716c9c19a1d0a12caf516536
```
3. Connect the server in VSCode
   1. Select kernel
   2. `shift+cmd+p` to open VS code's command pallete
   3. select "Jupyter: Specify Jupyter Server for Connections"
   4. copy and paste the server connection URI, hit Enter

## Install dependencies
Let's install PyTorch

In [5]:
!pip3 install torch

## Use PyTorch to manipulate data

In [2]:
import torch

### Create Tensors

First, use `arange` to create a 1-d vector.

In [7]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Use the vector's `shape` attribute to see its shape

In [8]:
x.shape

torch.Size([12])

Reshape it with the `reshape()` method

In [13]:
x = x.reshape(3, 4)

Confirm that it's reshaped

In [15]:
x.shape

torch.Size([3, 4])

Use the `numel()` method to calculate the total number of elements

In [16]:
x.numel()

12

Create a 3d(2x3x4) Tensor of zeros

In [19]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Create a 3-d(2x3x4) Tensor of ones

In [18]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Create a 2-d (3x4) Tensor of random numbers

In [20]:
torch.randn(3,4)

tensor([[-0.1344, -0.4637, -0.1622,  0.4566],
        [ 0.1342, -1.4693, -1.2002, -0.6071],
        [-0.1453,  0.1005, -1.3168,  1.4448]])

Create a Tensor from Python nd arrays

In [21]:
torch.tensor([[2,1,4,3], [1,2,3,4], [4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### Tensor operators

Element-wise operations.
Simple arithmetic operators works element-wise on Tensors of the same shape:

\+, \-, \*, /, **

In [22]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

Single operand operator also works on Tensors.

`torch.exp` returns a new tensor with the exponential of the input element (e to the power of x)

In [23]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

Concatenate tensors.
Dimension 0 is row, dimension 1 is column

In [5]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

Logical operator also works with Tensors element-wise.

In [7]:
X, Y, X == Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]))

Calculating the sum of a tensor returns a one element tensor.

In [8]:
X.sum()

tensor(66.)

### Broadcasting Mechanism
If you try to do operaions on two tensors of different shape (but the same number of dimensions), the broadcasting mechanism automatically copy the rows and columns needed to make the two tensors the same shape for the operation.

In the following example, both tensors will be broadcasted along the axis whose length is 1.

Tensor a
```
0
1
2
```
Will be
```
0 0
1 1
2 2
```
Tensor b
```
0 1
```
Will be
```
0 1
0 1
0 1
```
So that adding them together gives us
```
0 1
1 2
2 3
```

In [9]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b, a+b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

### Index and slices 

Just like Python arrays, you can use indices and slices to access part of a tensor.

In [11]:
X = torch.arange(16).reshape(4,4)
X, X[-1], X[1:3]

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]),
 tensor([12, 13, 14, 15]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [12]:
X[1, 2] = 9
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

We can use slices to assign the same value to multiple elements.

In [15]:
X = torch.arange(16).reshape(4,4)
X[0:2, 1:] = 12
X 

tensor([[ 0, 12, 12, 12],
        [ 4, 12, 12, 12],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

### Reuse memory
Be careful copying large tensors. Just reusing a variable will not reuse the memory, but using slice assign can reuse the memory.

In [17]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
before = id(Y) # id(X) returns the pointer of X
Y = X + Y
id(Y) == before

False

In [18]:
Z = torch.zeros_like(Y) # zeros_like returns a tensor of zero of the same shape
print('id(Z): ', id(Z))
Z[:] = X+Y
print('id(Z): ', id(Z))

id(Z):  4558019216
id(Z):  4558019216


### Type casting between PyTorch tensors and Python ndarrays

In [19]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [20]:
type(a), type(a.item()), type(float(a))

(torch.Tensor, float, float)